import unittest
from src.day4 import PuzzleDay4


class TestDay1(unittest.TestCase):
    def __init__(self, *args, **kwargs):
        self.filename = "data/test_day4.input"
        self.exp_random_order = [
            7,
            4,
            9,
            5,
            11,
            17,
            23,
            2,
            0,
            14,
            21,
            24,
            10,
            16,
            13,
            6,
            15,
            25,
            12,
            22,
            18,
            20,
            8,
            19,
            3,
            26,
            1,
        ]
        self.exp_boards[
            [
                22,
                13,
                17,
                11,
                0,
                8,
                2,
                23,
                4,
                24,
                21,
                9,
                14,
                16,
                7,
                6,
                10,
                3,
                18,
                5,
                1,
                12,
                20,
                15,
                19,
            ],
            [
                3,
                15,
                0,
                2,
                22,
                9,
                18,
                13,
                17,
                5,
                19,
                8,
                7,
                25,
                23,
                20,
                11,
                10,
                24,
                4,
                14,
                21,
                16,
                12,
                6,
            ],
            [
                14,
                21,
                17,
                24,
                4,
                10,
                16,
                15,
                9,
                19,
                18,
                8,
                23,
                26,
                20,
                22,
                11,
                13,
                6,
                5,
                2,
                0,
                12,
                3,
                7,
            ],
        ]

    def test_read_input_file_returns_report(self):
        puzzle = PuzzleDay4(self.filename)
        report = puzzle.read_input_file(self.filename)
        self.assertEqual(report, self.exp_data)


if __name__ == "__main__":
    unittest.main()
